---
- name: install docker
  hosts: "{{ HOSTS }}"
  become: yes

  tasks: 
  - name: install aptitude
    apt: 
      name: aptitude
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: install requiared   
    apt: name={{ item }} state=latest update_cache=yes
    loop: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common','python3-pip','virtualenv','python3-setuptools']
  
  - name: Add Docker url key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      update_cache: yes
      name: docker-ce  
      state: latest
    
  - name: install Docker Module for Python
    pip:
      name: docker
  
  - name: sudo from docker users
    shell: usermod -aG docker ubuntu

