---
- name: test
  hosts: Sacond

  become: yes

  tasks:
  - name: install Apache WebServer
    yum: name=httpd state=latest
  - name: Start Apache and Enable every boot
    service: name=httpd state=started enabled=yes

      




