---
- name: install maven
  hosts: "{{ HOSTS }}"
  become: yes
  vars: 
    maven_major: 3
    maven_version: 3.6.2
    maven_home_parent_directory: /opt
    maven_file_name: apache-maven-{{ maven_version }}-bin.tar.gz
    maven_download_url: 'http://www.apache.org/dist/maven/maven-{{ maven_major }}/{{ maven_version }}/binaries/{{ maven_file_name }}'
    maven_download_username: ''
    maven_download_password: ''
  
  tasks:
  - name: install aptitude
    apt:
      name: aptitude
      state: latest
      update_cache: yes
      force_apt_get: yes

  - name: Checking if Maven is already installed
    stat: 
      path: '{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}'
    register: maven_installed

  - name: Downloading Maven Binaries
    get_url:
      url: '{{ maven_download_url }}'
      dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
      url_username: '{{ maven_download_username }}'
      url_password: '{{ maven_download_password }}'
    when: not maven_installed.stat.exists

  - name: Unarchive Maven Binaries
    unarchive:
      src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
      dest: '{{ maven_home_parent_directory }}'
      copy: no
    when: not maven_installed.stat.exists

  - name: Remove old path configuration
    file:
      path: /etc/profile.d/maven.sh
      state: absent

  - name: Maven path configuration
    lineinfile:
      dest: /etc/profile.d/maven.sh
      line: '{{ item.line }}'
      create: yes
      state: present
    with_items:
      - { line: 'M2_HOME={{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}' }
      - { line: 'PATH=$PATH:$M2_HOME/bin' }

  - name: Cleaning Up
    file:
      state: absent
      path: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'


