---

- name: Apachi and my web page
  hosts: all 
  become: yes

  vars: 
    source_file: /etc/ansible/index.html
    destination_file: /var/www/html
 
  tasks:
  - name: check and print Lin version
    debug: var=ansible_os_family
  - block: #block for Redat
       - name: Install Apachi web Server for RedHat
         yum: name=httpd state=latest
      
       - name: Copy Mypage to server
         copy: src={{ source_file }} dest={{ destination_file }} mode=0555
         notify: restart Apache RedHat

       - name: Start server for RedHat
         service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - block:  # block for Debian
       - name: Install Apachi web Server for Debian
         apt: name=apache2 state=latest
       
       - name: Copy Mypage to server
         copy: src={{ source_file }} dest={{ destination_file }} mode=0555
         notify: restart Apache Debian

       - name: Start server for Debian
         service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers: 
  - name: restart Apache RedHat
    service: name=httpd state=restarted
  - name: restart Apache Debian
    service: name=apache2 state=restarted
